
name: Build & deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Ensures full checkout
          
      - name: List files
        run: |
          pwd
          ls -la

      - name: Installing Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 21.x

      - name: Installing NPM packages
        run: npm install

      - name: Building project
        run: npm run build
        env:
          NODE_ENV: production

      - name: Uploading production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: List files
        run: |
          pwd
          ls -la

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          
      - name: Downloading artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: List files
        run: |
          pwd
          ls -la
          
      - name: Deploying to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          publish_dir: ./dist
          force_orphan: true # Creates a clean, empty branch before pushing
          cname: ${{ secrets.CNAME }}
